service: slackgpt

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  stage: prod
  region: eu-west-1
  runtime: nodejs18.x
  deploymentMethod: direct
  environment:
    NODE_ENV: ${env:NODE_ENV}
    AWS_REGION: ${env:AWS_REGION}
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    CRYPTO_KEY: ${env:CRYPTO_KEY}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}

functions:
  slack:
    handler: 'src/index.handler'
    events:
      - http:
          path: slack/events
          method: post

resources:
  Resources:
    WorkspaceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Workspace
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
